env_name: CarRacing-v2
max_episode_steps: 600
num_episodes: 10
domain_randomize: true
continuous: true
render_mode: human
use_gae: false
gamma: 0.99
lr: 0.0001
value_coef: 0.5
entropy_coef: 0.01
hidden_dim: 256
batch_size: 64
checkpoint_dir: checkpoints
checkpoint_freq: 1
num_checkpoints: 5
