env_name: highway-fast-v0
config_dir: None
num_episodes: 2
max_episode_steps: 50
domain_randomize: true
continuous: true
render_mode: human
use_gae: false
gamma: 0.99
lr: 0.0003
lr_gamma: 0.1
value_coef: 0.5
entropy_coef: 0.01
hidden_dim: 128
batch_size: 128
checkpoint_dir: checkpoints
checkpoint_freq: 50
num_checkpoints: 5
tau: 0.99
alpha: 0.5
replay_buffer_capacity: 1024
replay_buffer_alpha: 0.5
