name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile

      - name: Create .nojekyll file
        run: touch docs/html/.nojekyll

      - name: Debug Contents of docs/html
        run: |
          echo "Listing contents of docs/html:"
          ls -R docs/html
          echo "Checking file permissions:"
          ls -l docs/html

      - name: Upload Doxygen Documentation as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: docs
        env:
          ACTIONS_STEP_DEBUG: true
