on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment and Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile

      - name: Ensure docs/html Directory Exists and Create .nojekyll
        run: |
          if [ ! -d "docs/html" ]; then
            echo "docs/html directory does not exist."
            exit 1
          else
            touch docs/html/.nojekyll
          fi

      - name: Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Ensure this matches your Ruby version

      - name: Install Gems and Build Jekyll Site
        run: |
          gem install bundler -v 2.4.22
          bundle install
          bundle exec jekyll build

      - name: Move Doxygen Documentation to _site
        run: |
          if [ ! -d "_site" ]; then
            echo "_site/ directory does not exist."
            exit 1
          else
            mv docs _site/  # Move docs/html to _site/
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
