name: Build and Deploy Jekyll Site

on:
  workflow_run:
    workflows: ["Doxygen GitHub Pages Deploy Action"]
    types:
      - completed
    branches:
      - gh-pages
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # Ensure this matches your Ruby version that matches our Jekyll setup

      - name: Install dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install

      - name: List Available Artifacts (Debug)
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/10304161409/artifacts

      - name: Download Doxygen Documentation
        uses: actions/download-artifact@v4
        with:
          name: doxygen-docs
          path: docs

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Move Doxygen Documentation
        run: mv docs _site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
